2016-10-14 16:47:38,614 INFO: finance hub startup [in /home/ubuntu/workspace/finance/app/__init__.py:49]
2016-10-14 16:49:07,822 INFO: finance hub startup [in /home/ubuntu/workspace/finance/app/__init__.py:49]
2016-10-14 16:49:11,568 INFO: Successfully connected to finance [in db_utils.py:15]
2016-10-14 19:13:59,546 INFO: finance hub startup [in /home/ubuntu/workspace/finance/app/__init__.py:49]
2016-10-14 19:14:01,363 INFO: Successfully connected to finance [in db_utils.py:22]
2016-10-14 19:15:25,821 INFO: finance hub startup [in /home/ubuntu/workspace/finance/app/__init__.py:49]
2016-10-14 19:15:26,731 INFO: Successfully connected to finance [in db_utils.py:22]
2016-10-14 19:15:26,731 INFO: DB SELECT ERROR:(1146, "Table 'finance.finance' doesn't exist") [in db_utils.py:37]
2016-10-14 19:16:05,703 INFO: finance hub startup [in /home/ubuntu/workspace/finance/app/__init__.py:49]
2016-10-14 19:16:06,596 INFO: Successfully connected to finance [in db_utils.py:22]
2016-10-14 19:16:06,597 INFO: DB SELECT ERROR:(1146, "Table 'finance.finance' doesn't exist") [in db_utils.py:38]
2016-10-14 19:16:19,630 INFO: finance hub startup [in /home/ubuntu/workspace/finance/app/__init__.py:49]
2016-10-14 19:16:20,640 INFO: Successfully connected to finance [in db_utils.py:22]
2016-10-14 19:16:20,641 INFO: DB SELECT ERROR:name 'exce_string' is not defined [in db_utils.py:38]
2016-10-14 19:16:39,156 INFO: finance hub startup [in /home/ubuntu/workspace/finance/app/__init__.py:49]
2016-10-14 19:16:40,061 INFO: Successfully connected to finance [in db_utils.py:22]
2016-10-14 19:16:51,012 INFO: finance hub startup [in /home/ubuntu/workspace/finance/app/__init__.py:49]
2016-10-14 19:16:52,203 INFO: Successfully connected to finance [in db_utils.py:22]
2016-10-14 19:16:52,204 INFO: DB SELECT ERROR:(1146, "Table 'finance.finance' doesn't exist") [in db_utils.py:38]
2016-10-14 19:17:12,213 INFO: finance hub startup [in /home/ubuntu/workspace/finance/app/__init__.py:49]
2016-10-14 19:17:13,188 INFO: Successfully connected to finance [in db_utils.py:22]
2016-10-14 19:17:13,189 INFO: DB SELECT ERROR:(1146, "Table 'finance.finance' doesn't exist") [in db_utils.py:38]
2016-10-14 19:17:33,193 INFO: finance hub startup [in /home/ubuntu/workspace/finance/app/__init__.py:49]
2016-10-14 19:17:34,042 INFO: Successfully connected to finance [in db_utils.py:22]
2016-10-14 19:19:18,724 INFO: finance hub startup [in /home/ubuntu/workspace/finance/app/__init__.py:49]
2016-10-14 19:19:19,445 INFO: Successfully connected to finance [in db_utils.py:22]
